
package vistas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import tpalumnoss.Alumno;
import static tpalumnoss.Alumno.listAlumnos;
import tpalumnoss.Inscripcion;
import tpalumnoss.Materia;



public class FormularioInscripcion extends javax.swing.JInternalFrame {

    public FormularioInscripcion() {
        initComponents();
        mostrarDatos();
    }
    private void mostrarDatos() {
        int cantidadAlumnos = Alumno.listAlumnos.size();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) jcboxAlumno.getModel();
        jcboxAlumno.setModel(modelo);
        for (int i = 0; i < cantidadAlumnos; i++) {
            modelo.addElement(listAlumnos.values());
        }

        int cantidadCursos = Materia.listaMaterias.size();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) jcboxMaterias.getModel();
        jcboxMaterias.setModel(modelo2);
        for (int i = 0; i < cantidadCursos; i++) {
            modelo2.addElement(Materia.listaMaterias.values());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcboxMaterias = new javax.swing.JComboBox<>();
        jcboxAlumno = new javax.swing.JComboBox<>();
        btnInscribir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setText("Formulario inscripcion");

        jLabel2.setText("Elija materia");

        jLabel3.setText("Elija alumno");

        jcboxMaterias.setSelectedIndex(-1);
        jcboxMaterias.setToolTipText("");
        jcboxMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMateriasActionPerformed(evt);
            }
        });

        jcboxAlumno.setSelectedIndex(-1);
        jcboxAlumno.setToolTipText("");

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcboxAlumno, 0, 145, Short.MAX_VALUE)
                                    .addComponent(jcboxMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscribir)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcboxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcboxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnSalir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcboxMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMateriasActionPerformed
        



        }//GEN-LAST:event_jcboxMateriasActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        Materia materia = (Materia) jcboxMaterias.getSelectedItem();
    Alumno alumno = (Alumno) jcboxAlumno.getSelectedItem();
    Inscripcion insc = new Inscripcion(alumno, materia);
    // Primero se pregunta si ya está matriculado
    if (!View.gestInsc.estaMatriculado(insc)) {
        View.gestInsc.agregarMatricula(insc);
        JOptionPane.showMessageDialog(null, "Matrícula agregada");
    } else {
        JOptionPane.showMessageDialog(null, "El alumno ya está matriculado en esta materia");
    }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<Alumno> jcboxAlumno;
    private javax.swing.JComboBox<Materia> jcboxMaterias;
    // End of variables declaration//GEN-END:variables
}
